<<<<<<< HEAD
import {MockServerClient} from "../../interfaces/mock-server-client";

export function mockServerClient(host: any, port: any, contextPath?: any, ...args: any[]): MockServerClient;
=======
/** Declaration file generated by dts-gen */

export function mockServerClient(host: any, port: any, contextPath?: any, ...args: any[]): any;
>>>>>>> a08ef9f175e29eda5ba4819e205ccd74acd73b6a
